Repository tjmelo/tmx-mercury, pull requests merged in 2023-01, with the labels that each got.

#52 Including structure test
  .husky/pre-commit
  README.md
  package.json
  src/Components/Cards/Cards.spec.tsx
  src/Components/Cards/Cards.tsx
  src/Components/Cards/index.ts
  src/Components/City/City.spec.tsx
  src/Components/City/City.tsx
  src/Components/City/index.ts
  src/Components/Entry/Entry.spec.tsx
  src/Components/Entry/Entry.tsx
  src/Components/Entry/index.ts
  src/Components/ListStates/ListState.spec.tsx
  src/Components/ListStates/ListState.tsx
  src/Components/ListStates/index.ts
  src/Components/Router.tsx
  src/Components/Search/Search.spec.tsx
  src/Components/Search/Search.tsx
  src/Components/Search/index.ts
Labels: enhancement

#54 Igniting project
  package-lock.json
Labels: dependencies

#55 Fixing bug and clean code
  src/App.scss
  src/Components/City/City.tsx
  src/Components/Entry/Entry.tsx
  src/Components/ListStates/ListState.spec.tsx
  src/Components/ListStates/ListState.tsx
  src/Components/Router.tsx
  src/Components/State.tsx
  src/service/RequestAPI.ts
Labels: bug, enhancement

#56 Fixing bugs
  src/App.scss
  src/Components/City/City.tsx
Labels: bug

#57 Improving app
  .eslintrc
  .prettierrc
  config/init.js
  config/prefetch.js
  config/prefetch.mjs
  config/prelint.js
  config/prelint.mjs
  package-lock.json
  package.json
  src/Components/Cards/Cards.spec.tsx
  src/Components/Cards/Cards.tsx
  src/Components/City/City.spec.tsx
  src/Components/City/City.tsx
  src/Components/Feedback/Feedback.spec.tsx
  src/Components/Feedback/Feedback.tsx
  src/Components/Feedback/index.ts
  src/Components/ListStates/ListState.spec.tsx
  src/Components/ListStates/ListState.tsx
  src/Components/Render.tsx
  src/Components/Render/Render.spec.tsx
  src/Components/Render/Render.tsx
  src/Components/Render/index.ts
  src/Components/Router.tsx
  src/Components/Search/Search.spec.tsx
  src/Components/Search/Search.tsx
  src/Components/State.tsx
  src/Components/State/State.spec.tsx
  src/Components/State/State.tsx
  src/Components/State/index.ts
  src/index.tsx
  src/service/RequestAPI.ts
  src/types/index.ts
  src/types/interfaces.ts
  src/types/types.ts
Labels: enhancement
