Repository tjmelo/tmx-mercury, pull requests merged in 2024-02, with the labels that each got.

#73 Improving app
  .github/workflows/checkout-ci.yml
  .github/workflows/image-ci.yml
  Dockerfile
  README.md
  compose.yml
  package-lock.json
  package.json
Labels: enhancement

#78 Fixing favicon path behavior
  public/index.html
Labels: bug

#75 Adding Notify System
  src/Components/Entry/Entry.spec.tsx
  src/Components/Entry/Entry.tsx
  src/service/NotifySystem.ts
Labels: enhancement

#79 Removing deploy in precommit instruction
  .husky/pre-commit
Labels: bug

#80 Update packages
  .babelrc
  .eslintrc
  Dockerfile
  package-lock.json
  package.json
  src/service/NotifySystem.ts
  tsconfig.json
Labels: dependencies

#81 update: Updating project version
  .editorconfig
  .env
  compose.yml
  package-lock.json
  package.json
Labels: enhancement

#82 Update README.md
  README.md
Labels: enhancement
